version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    # volumes:
    #   - ./client/internal:/app/internal
    depends_on:
      - server
