version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./proto:/app/proto
    ports:
      - "50051:50051"
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./proto:/app/proto
    depends_on:
      - server
  